on:
  release:
    types: [published]

jobs:
  
  notify_paris_sspcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/repository-dispatch@v1
      with:
        repository: InseeFrLab/paris-sspcloud
        event-type: onyxia_release
        client-payload: '{"release_tag_name": "${{github.event.release.tag_name}}"}'
        token: ${{secrets.PAT_FOR_REPOSITORY_DISPATCH}}